### ISSUE TITLE
Error Help!

### ISSUE THREAD

**Issue by loplewloplop** [alvinl/auto-trader#8]
C:\Users\user1\stem>node bin/stem auto.json

module.js:340
    throw err;
          ^
Error: Cannot find module 'steam'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\user1\stem\lib\index.js:13:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

C:\Users\user1\stem>

**Comment by alvinl** [comment]
Assuming you ran `npm install`, it failed and that's what is causing that error. See if [this issue](https://github.com/alvinl/auto-trader/issues/7) is of any help. Otherwise reread the instructions and check the troubleshooting section

Edit: Updated issue link

**Comment by alvinl** [comment]
Closing since this is an installation error.
